name: Build TreeHopper Tool

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build TreeHopper Tool
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build . -t francispion.azurecr.io/treehopper:${{ github.sha }} -f src/TreeHopper/Dockerfile
